/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './devices-directives';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
export class Wrapper_IsSmartTv {
  context:import0.IsSmartTv;
  changed:boolean;
  /*private*/ _isSmartTv:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isSmartTv = import1.UNINITIALIZED;
    this.context = new import0.IsSmartTv(p0,p1,p2);
  }
  check_isSmartTv(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isSmartTv,currValue))) {
      this.changed = true;
      this.context.isSmartTv = currValue;
      this._isSmartTv = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsDesktop {
  context:import0.IsDesktop;
  changed:boolean;
  /*private*/ _isDesktop:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isDesktop = import1.UNINITIALIZED;
    this.context = new import0.IsDesktop(p0,p1,p2);
  }
  check_isDesktop(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isDesktop,currValue))) {
      this.changed = true;
      this.context.isDesktop = currValue;
      this._isDesktop = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsTablet {
  context:import0.IsTablet;
  changed:boolean;
  /*private*/ _isTablet:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isTablet = import1.UNINITIALIZED;
    this.context = new import0.IsTablet(p0,p1,p2);
  }
  check_isTablet(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isTablet,currValue))) {
      this.changed = true;
      this.context.isTablet = currValue;
      this._isTablet = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsMobile {
  context:import0.IsMobile;
  changed:boolean;
  /*private*/ _isMobile:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isMobile = import1.UNINITIALIZED;
    this.context = new import0.IsMobile(p0,p1,p2);
  }
  check_isMobile(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isMobile,currValue))) {
      this.changed = true;
      this.context.isMobile = currValue;
      this._isMobile = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ShowItDevice {
  context:import0.ShowItDevice;
  changed:boolean;
  /*private*/ _showItDevice:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._showItDevice = import1.UNINITIALIZED;
    this.context = new import0.ShowItDevice(p0,p1,p2);
  }
  check_showItDevice(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._showItDevice,currValue))) {
      this.changed = true;
      this.context.showItDevice = currValue;
      this._showItDevice = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_HideItDevice {
  context:import0.HideItDevice;
  changed:boolean;
  /*private*/ _hideItDevice:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._hideItDevice = import1.UNINITIALIZED;
    this.context = new import0.HideItDevice(p0,p1,p2);
  }
  check_hideItDevice(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._hideItDevice,currValue))) {
      this.changed = true;
      this.context.hideItDevice = currValue;
      this._hideItDevice = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsIphone {
  context:import0.IsIphone;
  changed:boolean;
  /*private*/ _isIphone:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isIphone = import1.UNINITIALIZED;
    this.context = new import0.IsIphone(p0,p1,p2);
  }
  check_isIphone(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isIphone,currValue))) {
      this.changed = true;
      this.context.isIphone = currValue;
      this._isIphone = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsIpad {
  context:import0.IsIpad;
  changed:boolean;
  /*private*/ _isIphone:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isIphone = import1.UNINITIALIZED;
    this.context = new import0.IsIpad(p0,p1,p2);
  }
  check_isIphone(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isIphone,currValue))) {
      this.changed = true;
      this.context.isIphone = currValue;
      this._isIphone = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsAndroidMobile {
  context:import0.IsAndroidMobile;
  changed:boolean;
  /*private*/ _isAndroidMobile:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isAndroidMobile = import1.UNINITIALIZED;
    this.context = new import0.IsAndroidMobile(p0,p1,p2);
  }
  check_isAndroidMobile(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isAndroidMobile,currValue))) {
      this.changed = true;
      this.context.isAndroidMobile = currValue;
      this._isAndroidMobile = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsAndroidTablet {
  context:import0.IsAndroidTablet;
  changed:boolean;
  /*private*/ _isAndroidTablet:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isAndroidTablet = import1.UNINITIALIZED;
    this.context = new import0.IsAndroidTablet(p0,p1,p2);
  }
  check_isAndroidTablet(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isAndroidTablet,currValue))) {
      this.changed = true;
      this.context.isAndroidTablet = currValue;
      this._isAndroidTablet = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsWindowsPhone {
  context:import0.IsWindowsPhone;
  changed:boolean;
  /*private*/ _isWindowsPhone:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isWindowsPhone = import1.UNINITIALIZED;
    this.context = new import0.IsWindowsPhone(p0,p1,p2);
  }
  check_isWindowsPhone(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isWindowsPhone,currValue))) {
      this.changed = true;
      this.context.isWindowsPhone = currValue;
      this._isWindowsPhone = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ShowItStandard {
  context:import0.ShowItStandard;
  changed:boolean;
  /*private*/ _showItStandard:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._showItStandard = import1.UNINITIALIZED;
    this.context = new import0.ShowItStandard(p0,p1,p2);
  }
  check_showItStandard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._showItStandard,currValue))) {
      this.changed = true;
      this.context.showItStandard = currValue;
      this._showItStandard = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_HideItStandard {
  context:import0.HideItStandard;
  changed:boolean;
  /*private*/ _hideItStandard:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._hideItStandard = import1.UNINITIALIZED;
    this.context = new import0.HideItStandard(p0,p1,p2);
  }
  check_hideItStandard(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._hideItStandard,currValue))) {
      this.changed = true;
      this.context.hideItStandard = currValue;
      this._hideItStandard = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsPortrait {
  context:import0.IsPortrait;
  changed:boolean;
  /*private*/ _isPortrait:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isPortrait = import1.UNINITIALIZED;
    this.context = new import0.IsPortrait(p0,p1,p2);
  }
  check_isPortrait(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isPortrait,currValue))) {
      this.changed = true;
      this.context.isPortrait = currValue;
      this._isPortrait = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_IsLandscape {
  context:import0.IsLandscape;
  changed:boolean;
  /*private*/ _isLandscape:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._isLandscape = import1.UNINITIALIZED;
    this.context = new import0.IsLandscape(p0,p1,p2);
  }
  check_isLandscape(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._isLandscape,currValue))) {
      this.changed = true;
      this.context.isLandscape = currValue;
      this._isLandscape = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_DeviceInfo {
  context:import0.DeviceInfo;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.DeviceInfo(p0,p1);
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
export class Wrapper_DeviceStandardInfo {
  context:import0.DeviceStandardInfo;
  changed:boolean;
  /*private*/ _deviceStandardInfo:any;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this._deviceStandardInfo = import1.UNINITIALIZED;
    this.context = new import0.DeviceStandardInfo(p0,p1);
  }
  check_deviceStandardInfo(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._deviceStandardInfo,currValue))) {
      this.changed = true;
      this.context.deviceStandardInfo = currValue;
      this._deviceStandardInfo = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
export class Wrapper_OrientationInfo {
  context:import0.OrientationInfo;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.OrientationInfo(p0,p1);
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}