/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './pixelratio-directives';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_Is1xPixel {
    context: import0.Is1xPixel;
    changed: boolean;
    _is1xPixel: any;
    constructor(p0: any, p1: any, p2: any);
    check_is1xPixel(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsRetina {
    context: import0.IsRetina;
    changed: boolean;
    _isRetina: any;
    constructor(p0: any, p1: any, p2: any);
    check_isRetina(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_Is4k {
    context: import0.Is4k;
    changed: boolean;
    _isRetina: any;
    constructor(p0: any, p1: any, p2: any);
    check_isRetina(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_PixelRatioInfo {
    context: import0.PixelRatioInfo;
    changed: boolean;
    _pixelratioInfo: any;
    constructor(p0: any, p1: any);
    check_pixelratioInfo(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
