/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './browsers-directives';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_IsChrome {
    context: import0.IsChrome;
    changed: boolean;
    _isChrome: any;
    constructor(p0: any, p1: any, p2: any);
    check_isChrome(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsFirefox {
    context: import0.IsFirefox;
    changed: boolean;
    _isFirefox: any;
    constructor(p0: any, p1: any, p2: any);
    check_isFirefox(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsSafari {
    context: import0.IsSafari;
    changed: boolean;
    _isSafari: any;
    constructor(p0: any, p1: any, p2: any);
    check_isSafari(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsOpera {
    context: import0.IsOpera;
    changed: boolean;
    _isOpera: any;
    constructor(p0: any, p1: any, p2: any);
    check_isOpera(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsIE {
    context: import0.IsIE;
    changed: boolean;
    _isIE: any;
    constructor(p0: any, p1: any, p2: any);
    check_isIE(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_ShowItBrowser {
    context: import0.ShowItBrowser;
    changed: boolean;
    _showItBrowser: any;
    constructor(p0: any, p1: any, p2: any);
    check_showItBrowser(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_HideItBrowser {
    context: import0.HideItBrowser;
    changed: boolean;
    _hideItBrowser: any;
    constructor(p0: any, p1: any, p2: any);
    check_hideItBrowser(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsIE9 {
    context: import0.IsIE9;
    changed: boolean;
    _isIE9: any;
    constructor(p0: any, p1: any, p2: any);
    check_isIE9(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsIE10 {
    context: import0.IsIE10;
    changed: boolean;
    _isIE10: any;
    constructor(p0: any, p1: any, p2: any);
    check_isIE10(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsIE11 {
    context: import0.IsIE11;
    changed: boolean;
    _isIE11: any;
    constructor(p0: any, p1: any, p2: any);
    check_isIE11(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IsIE12 {
    context: import0.IsIE12;
    changed: boolean;
    _isIE12: any;
    constructor(p0: any, p1: any, p2: any);
    check_isIE12(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_ShowIEVersion {
    context: import0.ShowIEVersion;
    changed: boolean;
    _showIEVersion: any;
    constructor(p0: any, p1: any, p2: any);
    check_showIEVersion(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_HideIEVersion {
    context: import0.HideIEVersion;
    changed: boolean;
    _hideIEVersion: any;
    constructor(p0: any, p1: any, p2: any);
    check_hideIEVersion(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_BrowserInfo {
    context: import0.BrowserInfo;
    changed: boolean;
    _browserInfo: any;
    constructor(p0: any, p1: any);
    check_browserInfo(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_IeInfo {
    context: import0.IeInfo;
    changed: boolean;
    _ieInfo: any;
    constructor(p0: any, p1: any);
    check_ieInfo(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
