/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './responsive-window';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
export class Wrapper_ResponsiveWindow {
  context:import0.ResponsiveWindow;
  changed:boolean;
  /*private*/ _name:any;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this._name = import1.UNINITIALIZED;
    this.context = new import0.ResponsiveWindow(p0,p1);
  }
  check_name(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._name,currValue))) {
      this.changed = true;
      this.context.name = currValue;
      this._name = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) {
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
      this.context.ngDoCheck();
    }
    return changed;
  }
}