/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './responsive-window';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_ResponsiveWindow {
    context: import0.ResponsiveWindow;
    changed: boolean;
    _name: any;
    constructor(p0: any, p1: any);
    check_name(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
