/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './custom-sizes-directives';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_ShowItSizes {
    context: import0.ShowItSizes;
    changed: boolean;
    _showItSizes: any;
    constructor(p0: any, p1: any, p2: any);
    check_showItSizes(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_HideItSizes {
    context: import0.HideItSizes;
    changed: boolean;
    _hideItSizes: any;
    constructor(p0: any, p1: any, p2: any);
    check_hideItSizes(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
