/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './useragent';
import * as import1 from '@angular/core/src/linker/view';
export declare class Wrapper_UserAgentInfo {
    context: import0.UserAgentInfo;
    changed: boolean;
    constructor(p0: any);
    detectChangesInternal(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
