/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './responsive';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
export class Wrapper_Responsive {
  context:import0.Responsive;
  changed:boolean;
  /*private*/ _responsive:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._responsive = import1.UNINITIALIZED;
    this.context = new import0.Responsive(p0,p1,p2);
  }
  check_responsive(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._responsive,currValue))) {
      this.changed = true;
      this.context.responsive = currValue;
      this._responsive = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}