/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './responsive';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_Responsive {
    context: import0.Responsive;
    changed: boolean;
    _responsive: any;
    constructor(p0: any, p1: any, p2: any);
    check_responsive(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
