/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from './config/config';
import * as import3 from '@angular/core/src/di/injector';
class ResponsiveModuleInjector extends import0.NgModuleInjector<import1.ResponsiveModule> {
  _ResponsiveModule_0:import1.ResponsiveModule;
  __ResponsiveConfig_1:import2.ResponsiveConfig;
  __ResponsiveState_2:import2.ResponsiveState;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _ResponsiveConfig_1():import2.ResponsiveConfig {
    if ((this.__ResponsiveConfig_1 == null)) { (this.__ResponsiveConfig_1 = new import2.ResponsiveConfig(this.parent.get(import2.ResponsiveConfigInterface,(null as any)))); }
    return this.__ResponsiveConfig_1;
  }
  get _ResponsiveState_2():import2.ResponsiveState {
    if ((this.__ResponsiveState_2 == null)) { (this.__ResponsiveState_2 = new import2.ResponsiveState(this._ResponsiveConfig_1)); }
    return this.__ResponsiveState_2;
  }
  createInternal():import1.ResponsiveModule {
    this._ResponsiveModule_0 = new import1.ResponsiveModule();
    return this._ResponsiveModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ResponsiveModule)) { return this._ResponsiveModule_0; }
    if ((token === import2.ResponsiveConfig)) { return this._ResponsiveConfig_1; }
    if ((token === import2.ResponsiveState)) { return this._ResponsiveState_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ResponsiveModuleNgFactory:import0.NgModuleFactory<import1.ResponsiveModule> = new import0.NgModuleFactory(ResponsiveModuleInjector,import1.ResponsiveModule);