/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from './config/config';
export const ResponsiveModuleNgFactory:i0.NgModuleFactory<i1.ResponsiveModule> = i0.ɵcmf(i1.ResponsiveModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.ResponsiveConfig,i2.ResponsiveConfig,[[2,i2.ResponsiveConfigInterface]]),
          i0.ɵmpd(4608,i2.ResponsiveState,i2.ResponsiveState,[[2,i2.ResponsiveConfig]]),
          i0.ɵmpd(512,i1.ResponsiveModule,i1.ResponsiveModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovREVWL3Byb2plY3RzL25nMi1yZXNwb25zaXZlL3NyYy9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9ERVYvcHJvamVjdHMvbmcyLXJlc3BvbnNpdmUvc3JjL2luZGV4LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
