import { NgModule } from '@angular/core';
import { ResponsiveConfig, ResponsiveState } from './@core/index';
import {
    BOOTSTRAP_DIRECTIVES, BROWSER_DIRECTIVES, BROWSER_INFO_RX, IE_INFO_RX,
    CUSTOMSIZES_DIRECTIVES, DEVICES_DIRECTIVES, PIXELRATIO_DIRECTIVES, RESPONSIVE_DIRECTIVE,
    RESPONSIVEWINDOW_DIRECTIVE, USERAGENT_INFO_DIRECTIVE, USERAGENT_INFO_RX, RESPONSIVE_SIZE_INFO_DIRECTIVE,
    RESPONSIVE_SIZE_INFO_RX
} from './@directives/index';

@NgModule({
    declarations:
    [
        BOOTSTRAP_DIRECTIVES,
        BROWSER_DIRECTIVES,
        CUSTOMSIZES_DIRECTIVES,
        DEVICES_DIRECTIVES,
        PIXELRATIO_DIRECTIVES,
        RESPONSIVE_DIRECTIVE,
        RESPONSIVEWINDOW_DIRECTIVE,
        USERAGENT_INFO_DIRECTIVE,
        RESPONSIVE_SIZE_INFO_DIRECTIVE
    ],
    exports:
    [
        BOOTSTRAP_DIRECTIVES,
        BROWSER_DIRECTIVES,
        CUSTOMSIZES_DIRECTIVES,
        DEVICES_DIRECTIVES,
        PIXELRATIO_DIRECTIVES,
        RESPONSIVE_DIRECTIVE,
        RESPONSIVEWINDOW_DIRECTIVE,
        USERAGENT_INFO_DIRECTIVE,
        RESPONSIVE_SIZE_INFO_DIRECTIVE
    ],
    providers:
    [
        ResponsiveState,
        ResponsiveConfig,
        RESPONSIVE_SIZE_INFO_RX,
        USERAGENT_INFO_RX,
        BROWSER_INFO_RX,
        IE_INFO_RX
    ]
})
export class ResponsiveModule {}
