/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './bootstrap-directives';
import * as import3 from '@angular/core/src/linker/view';
export declare class Wrapper_XL {
    context: import0.XL;
    changed: boolean;
    _xl: any;
    constructor(p0: any, p1: any, p2: any);
    check_xl(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_LG {
    context: import0.LG;
    changed: boolean;
    _lg: any;
    constructor(p0: any, p1: any, p2: any);
    check_lg(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_MD {
    context: import0.MD;
    changed: boolean;
    _md: any;
    constructor(p0: any, p1: any, p2: any);
    check_md(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_SM {
    context: import0.SM;
    changed: boolean;
    _sm: any;
    constructor(p0: any, p1: any, p2: any);
    check_sm(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_XS {
    context: import0.XS;
    changed: boolean;
    _xs: any;
    constructor(p0: any, p1: any, p2: any);
    check_xs(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_ShowItBootstrap {
    context: import0.ShowItBootstrap;
    changed: boolean;
    _showItBootstrap: any;
    constructor(p0: any, p1: any, p2: any);
    check_showItBootstrap(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_HideItBootstrap {
    context: import0.HideItBootstrap;
    changed: boolean;
    _hideItBootstrap: any;
    constructor(p0: any, p1: any, p2: any);
    check_hideItBootstrap(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare class Wrapper_ResponsiveSizeInfo {
    context: import0.ResponsiveSizeInfo;
    changed: boolean;
    _responsiveSizeInfo: any;
    constructor(p0: any, p1: any);
    check_responsiveSizeInfo(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    detectChangesInternal(view: import3.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
