/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './bootstrap-directives';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
export class Wrapper_XL {
  context:import0.XL;
  changed:boolean;
  /*private*/ _xl:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._xl = import1.UNINITIALIZED;
    this.context = new import0.XL(p0,p1,p2);
  }
  check_xl(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._xl,currValue))) {
      this.changed = true;
      this.context.xl = currValue;
      this._xl = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_LG {
  context:import0.LG;
  changed:boolean;
  /*private*/ _lg:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._lg = import1.UNINITIALIZED;
    this.context = new import0.LG(p0,p1,p2);
  }
  check_lg(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._lg,currValue))) {
      this.changed = true;
      this.context.lg = currValue;
      this._lg = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_MD {
  context:import0.MD;
  changed:boolean;
  /*private*/ _md:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._md = import1.UNINITIALIZED;
    this.context = new import0.MD(p0,p1,p2);
  }
  check_md(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._md,currValue))) {
      this.changed = true;
      this.context.md = currValue;
      this._md = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_SM {
  context:import0.SM;
  changed:boolean;
  /*private*/ _sm:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._sm = import1.UNINITIALIZED;
    this.context = new import0.SM(p0,p1,p2);
  }
  check_sm(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._sm,currValue))) {
      this.changed = true;
      this.context.sm = currValue;
      this._sm = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_XS {
  context:import0.XS;
  changed:boolean;
  /*private*/ _xs:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._xs = import1.UNINITIALIZED;
    this.context = new import0.XS(p0,p1,p2);
  }
  check_xs(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._xs,currValue))) {
      this.changed = true;
      this.context.xs = currValue;
      this._xs = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ShowItBootstrap {
  context:import0.ShowItBootstrap;
  changed:boolean;
  /*private*/ _showItBootstrap:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._showItBootstrap = import1.UNINITIALIZED;
    this.context = new import0.ShowItBootstrap(p0,p1,p2);
  }
  check_showItBootstrap(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._showItBootstrap,currValue))) {
      this.changed = true;
      this.context.showItBootstrap = currValue;
      this._showItBootstrap = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_HideItBootstrap {
  context:import0.HideItBootstrap;
  changed:boolean;
  /*private*/ _hideItBootstrap:any;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this._hideItBootstrap = import1.UNINITIALIZED;
    this.context = new import0.HideItBootstrap(p0,p1,p2);
  }
  check_hideItBootstrap(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._hideItBootstrap,currValue))) {
      this.changed = true;
      this.context.hideItBootstrap = currValue;
      this._hideItBootstrap = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ResponsiveSizeInfo {
  context:import0.ResponsiveSizeInfo;
  changed:boolean;
  /*private*/ _responsiveSizeInfo:any;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this._responsiveSizeInfo = import1.UNINITIALIZED;
    this.context = new import0.ResponsiveSizeInfo(p0,p1);
  }
  check_responsiveSizeInfo(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._responsiveSizeInfo,currValue))) {
      this.changed = true;
      this.context.responsiveSizeInfo = currValue;
      this._responsiveSizeInfo = currValue;
    }
  }
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}